version: '3.8'

services:
  corgfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: pnpm dev
    stdin_open: true
    tty: true

  corgfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
